# Tests for issue #164 — `lambda_selection` parameter on `fetwfe()` /
# `betwfe()` (v1.13.0): adds 10-fold CV alongside the BIC selection
# path, changes the default from BIC to CV.
#
# Coverage:
#   1. Default `lambda_selection` is `"cv"`.
#   2. CV path produces finite, sensible results.
#   3. CV path is deterministic for the same `cv_seed`.
#   4. CV path differs for different `cv_seed` values.
#   5. BIC path produces byte-identical results to a small fixed-θ DGP
#      reference. The "byte-identical-to-v1.12.0" claim is implicit:
#      the BIC path's only behavioral change is that it is now reached
#      via a dispatch on `lambda_selection = "bic"` instead of being
#      the only option — same internal call to `getBetaBIC()`, same
#      result. Reference values were generated by running v1.13.0's
#      CV/BIC dispatch with `lambda_selection = "bic"` on the fixture
#      below; future refactors that disturb the BIC path will cause
#      this test to fail.
#   6. Invalid `lambda_selection` errors cleanly via the
#      collect-all-violations validator (not `match.arg`).
#   7. `cv_folds < 2` errors cleanly (bounds check).
#   8. `glance()` exposes the three new slots.
#   9. Both paths are exposed for `betwfe()` as well as `fetwfe()`.
#  10. Coverage validation: a small fixed-θ test asserts that
#      `lambda_selection = "cv"` on a representative DGP gives
#      `mean(att_hat - true_att)` bias `< 0.10` in absolute value.
#      This is a coverage-direction check, not a stat-test — the
#      SPEC's empirical validation (Phase B / B-extended) already
#      covered the statistical claim.

library(testthat)
library(fetwfe)

# ------------------------------------------------------------------------------
# Shared fixture: small fixed-θ panel.
# ------------------------------------------------------------------------------

.lambda_sel_fixture <- function(seed = 2026, N = 120) {
	sim_coefs <- genCoefs(
		G = 3,
		T = 5,
		d = 2,
		density = 0.5,
		eff_size = 2,
		seed = seed
	)
	simulateData(
		sim_coefs,
		N = N,
		sig_eps_sq = 1,
		sig_eps_c_sq = 0.5,
		seed = seed
	)
}

# ------------------------------------------------------------------------------
# Test 1: default lambda_selection is "cv".
# ------------------------------------------------------------------------------

test_that("default lambda_selection is 'cv'", {
	sim <- .lambda_sel_fixture()
	res <- fetwfeWithSimulatedData(sim)
	expect_identical(res$lambda_selection, "cv")
	expect_identical(res$cv_folds, 10L)
	# Default cv_seed = as.integer(N * T) = 120 * 5 = 600
	expect_identical(res$cv_seed, 600L)
})

test_that("default lambda_selection is 'cv' for betwfe too", {
	sim <- .lambda_sel_fixture()
	res <- betwfeWithSimulatedData(sim)
	expect_identical(res$lambda_selection, "cv")
	expect_identical(res$cv_folds, 10L)
	expect_identical(res$cv_seed, 600L)
})

# ------------------------------------------------------------------------------
# Test 2: CV path produces finite, sensible results.
# ------------------------------------------------------------------------------

test_that("CV path produces finite att_hat, att_se, lambda_star", {
	sim <- .lambda_sel_fixture()
	res <- fetwfeWithSimulatedData(sim)

	expect_true(is.finite(res$att_hat))
	expect_true(is.finite(res$att_se))
	expect_true(is.finite(res$lambda_star))
	expect_gt(res$att_se, 0)
	expect_gt(res$lambda_star, 0)
	expect_gte(res$lambda_star_model_size, 1L)
})

# ------------------------------------------------------------------------------
# Test 3: CV is deterministic for the same cv_seed.
# ------------------------------------------------------------------------------

test_that("CV path is deterministic for the same cv_seed", {
	sim <- .lambda_sel_fixture()
	res1 <- fetwfeWithSimulatedData(sim, cv_seed = 42L)
	res2 <- fetwfeWithSimulatedData(sim, cv_seed = 42L)
	expect_identical(res1$att_hat, res2$att_hat)
	expect_identical(res1$att_se, res2$att_se)
	expect_identical(res1$lambda_star, res2$lambda_star)
	expect_identical(res1$cv_seed, 42L)
})

test_that("CV path with cv_seed = NULL defaults to as.integer(N * T)", {
	sim <- .lambda_sel_fixture(N = 120)
	res_default <- fetwfeWithSimulatedData(sim)
	expect_identical(res_default$cv_seed, 600L) # 120 * 5

	# Calling explicitly with the same seed should yield byte-identical
	# results.
	res_explicit <- fetwfeWithSimulatedData(sim, cv_seed = 600L)
	expect_identical(res_default$att_hat, res_explicit$att_hat)
})

# ------------------------------------------------------------------------------
# Test 4: CV varies for different cv_seed values.
# ------------------------------------------------------------------------------

test_that("CV path varies for different cv_seed values", {
	sim <- .lambda_sel_fixture()
	# Pre-computed seeds known to produce different CV-selected lambdas
	# on this DGP. (Some seed pairs collide because CV picks the same
	# lambda index when fold assignment doesn't shift the optimum;
	# 100 vs 7 is empirically different on this fixture.)
	res_a <- fetwfeWithSimulatedData(sim, cv_seed = 100L)
	res_b <- fetwfeWithSimulatedData(sim, cv_seed = 7L)
	expect_false(isTRUE(all.equal(res_a$att_hat, res_b$att_hat)))
})

# ------------------------------------------------------------------------------
# Test 5: BIC path produces byte-identical results (regression).
#
# These reference values were generated by running v1.13.0's BIC
# dispatch on the fixture above. The BIC path's only behavioral change
# in v1.13.0 is that it is reached via `lambda_selection = "bic"`
# rather than being the only option; the internal call to
# `getBetaBIC()` is byte-identical to v1.12.0's. Future refactors
# that disturb the BIC path will cause this test to fail.
# ------------------------------------------------------------------------------

test_that("BIC path produces byte-identical results on a small fixed-theta DGP", {
	sim <- .lambda_sel_fixture()
	res <- fetwfeWithSimulatedData(sim, lambda_selection = "bic")

	expect_identical(res$lambda_selection, "bic")
	expect_identical(res$cv_folds, NA_integer_)
	expect_identical(res$cv_seed, NA_integer_)

	# Numerical lock-in — tolerance 1e-12 catches any drift in the BIC
	# math from refactoring while accommodating cross-platform float drift
	# on grpreg+BLAS.
	expect_equal(res$att_hat, 0.4480082058461672, tolerance = 1e-12)
	expect_equal(res$att_se, 0.1356706033541936, tolerance = 1e-12)
	expect_equal(res$lambda_star, 0.01246630388611171, tolerance = 1e-12)
	# Feature count now excludes the always-present intercept (#269); was 18L when
	# the intercept was counted. The locked att/se/lambda_star above are unchanged
	# by that switch (it is a constant offset on the BIC, so selection is identical).
	expect_equal(res$lambda_star_model_size, 17L)
})

test_that("BETWFE BIC path produces byte-identical results", {
	sim <- .lambda_sel_fixture()
	res <- betwfeWithSimulatedData(sim, lambda_selection = "bic")

	expect_identical(res$lambda_selection, "bic")
	# Reference values from v1.13.0 BIC dispatch on the same fixture.
	expect_equal(res$att_hat, 0.4383080388062255, tolerance = 1e-12)
	expect_equal(res$att_se, 0.1329024923053161, tolerance = 1e-12)
	expect_equal(res$lambda_star, 0.02685783754871834, tolerance = 1e-12)
})

# ------------------------------------------------------------------------------
# Test 6: invalid lambda_selection errors cleanly.
# ------------------------------------------------------------------------------

test_that("invalid lambda_selection errors cleanly", {
	df <- generate_panel_data()
	expect_error(
		fetwfe(
			pdata = df,
			time_var = "time",
			unit_var = "unit",
			treatment = "treatment",
			covs = c("cov1", "cov2"),
			response = "y",
			lambda_selection = "aic"
		),
		"lambda_selection must be a single character"
	)
})

test_that("bad lambda_selection + cv_folds + cv_seed surface as a single Invalid inputs block", {
	# Regression test for the post-execution review's R2 note (#164):
	# `match.arg(lambda_selection)` used to fire before the
	# collect-all-violations validator, so a user passing multiple
	# bad arguments only saw the lambda_selection error first.
	# v1.13.0 removes that match.arg from user-facing wrappers, so
	# the validator surfaces all three errors together.
	df <- generate_panel_data()
	err <- tryCatch(
		fetwfe(
			pdata = df,
			time_var = "time",
			unit_var = "unit",
			treatment = "treatment",
			covs = c("cov1", "cov2"),
			response = "y",
			lambda_selection = "aic",
			cv_folds = 1L,
			cv_seed = "not_an_integer"
		),
		error = function(e) conditionMessage(e)
	)
	expect_match(err, "Invalid inputs:")
	expect_match(err, "lambda_selection")
	expect_match(err, "cv_folds")
	expect_match(err, "cv_seed")
})

# ------------------------------------------------------------------------------
# Test 7: cv_folds < 2 errors cleanly.
# ------------------------------------------------------------------------------

test_that("cv_folds < 2 errors cleanly", {
	df <- generate_panel_data()
	expect_error(
		fetwfe(
			pdata = df,
			time_var = "time",
			unit_var = "unit",
			treatment = "treatment",
			covs = c("cov1", "cov2"),
			response = "y",
			cv_folds = 1L
		),
		"cv_folds"
	)
})

test_that("non-integer cv_folds errors cleanly", {
	df <- generate_panel_data()
	expect_error(
		fetwfe(
			pdata = df,
			time_var = "time",
			unit_var = "unit",
			treatment = "treatment",
			covs = c("cov1", "cov2"),
			response = "y",
			cv_folds = 3.5
		),
		"cv_folds"
	)
})

test_that("invalid cv_seed errors cleanly", {
	df <- generate_panel_data()
	expect_error(
		fetwfe(
			pdata = df,
			time_var = "time",
			unit_var = "unit",
			treatment = "treatment",
			covs = c("cov1", "cov2"),
			response = "y",
			cv_seed = "not_an_integer"
		),
		"cv_seed"
	)
})

# ------------------------------------------------------------------------------
# Test 8: glance() exposes the new slots.
# ------------------------------------------------------------------------------

test_that("glance.fetwfe exposes lambda_selection / cv_folds / cv_seed", {
	skip_if_not_installed("broom")
	sim <- .lambda_sel_fixture()
	res <- fetwfeWithSimulatedData(sim, cv_seed = 42L)
	gl <- broom::glance(res)
	expect_true(all(
		c("lambda_selection", "cv_folds", "cv_seed") %in% names(gl)
	))
	expect_identical(gl$lambda_selection, "cv")
	expect_identical(gl$cv_folds, 10L)
	expect_identical(gl$cv_seed, 42L)

	# BIC path: cv_folds / cv_seed should be NA_integer_.
	res_bic <- fetwfeWithSimulatedData(sim, lambda_selection = "bic")
	gl_bic <- broom::glance(res_bic)
	expect_identical(gl_bic$lambda_selection, "bic")
	expect_identical(gl_bic$cv_folds, NA_integer_)
	expect_identical(gl_bic$cv_seed, NA_integer_)
})

test_that("glance.betwfe exposes lambda_selection / cv_folds / cv_seed", {
	skip_if_not_installed("broom")
	sim <- .lambda_sel_fixture()
	res <- betwfeWithSimulatedData(sim, cv_seed = 42L)
	gl <- broom::glance(res)
	expect_true(all(
		c("lambda_selection", "cv_folds", "cv_seed") %in% names(gl)
	))
	expect_identical(gl$lambda_selection, "cv")
})

# ------------------------------------------------------------------------------
# Test 9: betwfe() exposes the same parameters and dispatch as fetwfe().
# ------------------------------------------------------------------------------

test_that("betwfe() supports lambda_selection / cv_folds / cv_seed", {
	sim <- .lambda_sel_fixture()
	res_cv <- betwfeWithSimulatedData(sim, lambda_selection = "cv")
	res_bic <- betwfeWithSimulatedData(sim, lambda_selection = "bic")

	expect_identical(res_cv$lambda_selection, "cv")
	expect_identical(res_bic$lambda_selection, "bic")

	# CV deterministic.
	res_cv2 <- betwfeWithSimulatedData(sim, cv_seed = 7L)
	res_cv3 <- betwfeWithSimulatedData(sim, cv_seed = 7L)
	expect_identical(res_cv2$att_hat, res_cv3$att_hat)
})

# ------------------------------------------------------------------------------
# Test 10: CV coverage validation — a SMALL fast DGP with 10 reps.
#
# This is a smoke test, NOT a re-validation of Phase B. The SPEC's
# acceptance criterion #5: "a small fixed-θ test asserts that
# `lambda_selection = "cv"` on a single representative DGP gives
# `mean(att_hat - true_att)` bias `< 0.10` in absolute value. This is
# a coverage-direction check, not a stat-test — the SPEC's empirical
# validation already covered the statistical claim."
#
# DGP: paper's first-simulation downscope (R=3, T=5, d=2, density=0.5,
# eff_size=2). N=200, 10 reps. Runs in seconds.
# ------------------------------------------------------------------------------

test_that("CV path has |bias| < 0.10 on a representative DGP (smoke test)", {
	skip_on_cran()

	template <- genCoefs(
		G = 3,
		T = 5,
		d = 2,
		density = 0.5,
		eff_size = 2,
		seed = 7777L
	)
	te_truth <- getTes(template)

	n_reps <- 10L
	biases <- numeric(n_reps)
	# As of #250 the panel RNG is controlled by the `seed` argument to
	# simulateData() (it no longer reuses coefs$seed); pass a distinct
	# `seed = 13000L + i` per rep to vary the noise across replications.
	for (i in seq_len(n_reps)) {
		sim <- simulateData(
			template,
			N = 200,
			sig_eps_sq = 1,
			sig_eps_c_sq = 0.5,
			seed = 13000L + i
		)
		# True ATT = sum(actual_cohort_tes * pi_cond) where pi_cond is
		# the in-sample treated proportions (excluding never-treated).
		pi_cond <- sim$indep_counts[-1] / sum(sim$indep_counts[-1])
		true_att <- sum(te_truth$actual_cohort_tes * pi_cond)
		res <- fetwfeWithSimulatedData(sim)
		biases[i] <- res$att_hat - true_att
	}
	mean_bias <- mean(biases)
	# Coverage-direction check: |bias| should be small, not statistically
	# negligible. Phase B's main DGP at N=200 gave CV-bridge bias = -0.069
	# at 100 reps; we expect similar magnitude at 10 reps on this DGP.
	# Tolerance 0.10 is loose enough to absorb 10-rep Monte Carlo error.
	expect_lt(abs(mean_bias), 0.10)
})

# ------------------------------------------------------------------------------
# Test: getBetaCV() preserves caller's .Random.seed (regression for #177).
#
# Before the fix, `set.seed(cv_seed)` inside getBetaCV() leaked into the
# caller's .GlobalEnv$.Random.seed, so a second set.seed(K) + runif() after
# the fit would diverge from a baseline set.seed(K) + runif() without the
# fit. The BIC path never mutated RNG (no set.seed call); we lock BOTH paths
# now so a future regression on either is caught.
# ------------------------------------------------------------------------------

test_that("CV path preserves caller's .Random.seed (#177)", {
	sim <- .lambda_sel_fixture()
	set.seed(42L)
	before <- runif(3L)
	set.seed(42L)
	invisible(fetwfeWithSimulatedData(sim))
	after <- runif(3L)
	expect_identical(before, after)
})

test_that("BIC path preserves caller's .Random.seed (#177)", {
	sim <- .lambda_sel_fixture()
	set.seed(42L)
	before <- runif(3L)
	set.seed(42L)
	invisible(fetwfeWithSimulatedData(sim, lambda_selection = "bic"))
	after <- runif(3L)
	expect_identical(before, after)
})

# ------------------------------------------------------------------------------
# (#185 G1): the default CV path composes with se_type = "cluster" and with
# add_ridge = TRUE -- cross-paths the other CV tests above leave unexercised.
# Both work empirically; this locks the cross-path behavior so a regression on
# either the cluster sandwich or the ridge augmentation under CV is caught.
# ------------------------------------------------------------------------------
test_that("CV path composes with se_type = 'cluster' and with add_ridge", {
	sim <- .lambda_sel_fixture()

	res_cl <- fetwfeWithSimulatedData(sim, se_type = "cluster")
	expect_identical(res_cl$lambda_selection, "cv")
	expect_identical(res_cl$se_type, "cluster")
	expect_true(is.finite(res_cl$att_hat))
	expect_true(is.finite(res_cl$att_se))
	expect_gt(res_cl$att_se, 0)

	res_ridge <- fetwfeWithSimulatedData(sim, add_ridge = TRUE)
	expect_identical(res_ridge$lambda_selection, "cv")
	expect_true(is.finite(res_ridge$att_hat))
	expect_true(is.finite(res_ridge$att_se))
})

# ------------------------------------------------------------------------------
# (#185 IC1): lambda.max / lambda.min / nlambda are silently ignored under the
# default lambda_selection = "cv" (cross-validation builds its own grid). Warn
# so the user isn't surprised; stay silent on the BIC path and on cv with the
# default grid.
# ------------------------------------------------------------------------------
test_that("cv path warns when lambda.max / lambda.min / nlambda are supplied", {
	sim <- .lambda_sel_fixture()
	expect_warning(
		fetwfeWithSimulatedData(sim, lambda.max = 5),
		"ignored under lambda_selection = 'cv'",
		fixed = TRUE
	)
	expect_warning(
		fetwfeWithSimulatedData(sim, nlambda = 50L),
		"ignored under lambda_selection = 'cv'",
		fixed = TRUE
	)
	# betwfe() shares the same dispatch.
	expect_warning(
		betwfeWithSimulatedData(sim, lambda.min = 0.01),
		"ignored under lambda_selection = 'cv'",
		fixed = TRUE
	)
	# BIC path uses the supplied grid -> no IC1 warning.
	expect_no_warning(
		fetwfeWithSimulatedData(sim, lambda_selection = "bic", lambda.max = 5)
	)
	# CV with the default grid -> no warning.
	expect_no_warning(fetwfeWithSimulatedData(sim))
})
